### ISSUE TITLE
Merge Modified_README branch into Main

### ISSUE THREAD

**Issue by AmyOlex** [Aish97-ux/CCTR691_Athena-#1]
All of the elements you need are here.  To complete the lab you can edit the readme file in the modified_README branch, then commit and push that branch up to GitHub.  From this point you can then merge the branch with your Main branch so that you do not see it any longer.  Your will need to pull those changes back down to your laptop.

For future repositories, it is customary to not have any type of punctuation at the end, so aim to end the repo name with a letter or number.  It is fine for this class however.

Please close this issue once completed.

**Comment by Aish97-ux** [comment]
done
